
shared:
  dataset:             'RossmanSales'
  backbone:            'S4'
  random_seed:         42
  data_split:          0.8  # train-test split
  beta_0:              0.0001
  beta_T:              0.02
  timesteps:           200
  hdim:                64
  lr:                  0.0001
  diff_batch_size:     1024
  layers:              4
  window_size:         32 # >0, power of 2
  stride:              1  # <= window_size
  num_res_layers:      4
  res_channels:        64
  skip_channels:       64
  diff_step_embed_in:  32
  diff_step_embed_mid: 64
  diff_step_embed_out: 64
  s4_lmax:             100
  s4_dstate:           64
  s4_dropout:          0.0
  s4_bidirectional:    True
  s4_layernorm:        True
  propCycEnc:          False
training:
  epochs:              100
synthesis:
  synth_mask:          'C' # C = coarse, M = medium, F = fine
  n_trials:            1   # synthesis trials

autoencoder: # optimized from hyperparameter search
  layer1_dim:          21    # size of hidden dimension
  layer2_dim:          9
  latent_dim:          4     # num of features in latent layer
  dropout_prob:        0.15
  ae_training_epochs:  100
  ae_batch_size:       126
  ae_optimizer_lr:     0.0011
  weight_decay:        0.00001
  training_patience:   70
  scheduler_patience:  70
  scheduler_mode:      'min'
  scheduler_factor:    0.8

latent_diffusion:        # LDM
  latent_batch_size:          128    # 
  latent_lr:                  0.0001 # Learning rate specific to the latent diffusion model
  latent_epochs:              100    # Number of epochs specific to the latent diffusion model
  latent_beta_0:              0.0001 # Beta start for the latent diffusion schedule
  latent_beta_T:              0.02   # Beta end for the latent diffusion schedule
  latent_timesteps:           200    # Number of diffusion steps for the latent diffusion model
  latent_num_res_layers:      2      # Number of residual layers in the LDM's denoiser
  latent_res_channels:        128    # Channels in residual blocks for the LDM's denoiser
  latent_skip_channels:       64     # Channels in skip connections for the LDM's denoiser
  latent_diff_step_embed_in:  32     # Input dim for time embedding in LDM
  latent_diff_step_embed_mid: 64     # Mid dim for time embedding in LDM
  latent_diff_step_embed_out: 64     # Output dim for time embedding in LDM
  latent_s4_lmax:             100    # S4 lmax for the LDM's denoiser (should be related to latent sequence length)
  latent_s4_dstate:           32     # S4 state dimension for the LDM's denoiser
  latent_s4_dropout:          0.0    # S4 dropout for the LDM's denoiser
  propCycEnc:                 False
  num_samples:                500
